<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class ContatosOutput implements \JsonSerializable {
			
		private $id;
		private $contato;
		private $nome;
		private $email;
		private $celular;
		private $cadastrado;
		private $modificado;
		private $situacoes_contatosOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getContato() {
			return $this->contato;
		}
		
		public function setContato($contato) {
			$this->contato = $contato;
		}
					
		public function getNome() {
			return $this->nome;
		}
		
		public function setNome($nome) {
			$this->nome = $nome;
		}
					
		public function getEmail() {
			return $this->email;
		}
		
		public function setEmail($email) {
			$this->email = $email;
		}
					
		public function getCelular() {
			return $this->celular;
		}
		
		public function setCelular($celular) {
			$this->celular = $celular;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getSituacoes_contatosOutput() {
			return $this->situacoes_contatosOutput;
		}
		
		public function setSituacoes_contatosOutput($situacoes_contatosOutput) {
			$this->situacoes_contatosOutput = $situacoes_contatosOutput;
		}

		public function getOutput($contatos) {
			if (!is_null($contatos)) {
				$contatosOutput = new model\ContatosOutput();
				$contatosOutput->setId($contatos->getId());
				$contatosOutput->setContato($contatos->getContato());
				$contatosOutput->setNome($contatos->getNome());
				$contatosOutput->setEmail($contatos->getEmail());
				$contatosOutput->setCelular($contatos->getCelular());
				$situacoes_contatosOutput = new model\Situacoes_contatosOutput();
				$contatosOutput->setSituacoes_contatosOutput($situacoes_contatosOutput->getOutput($contatos->getSituacoes_contatos()));
				return $contatosOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($contatosList) {
			$contatosOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($contatosList); $x++) {
				$contatosOutputList[$count] = $this->getOutput($contatosList[$x]);
				$count++;
			}
			return $contatosOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>