<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 

	class Contatos {
			
		private $id;
		private $contato;
		private $nome;
		private $email;
		private $celular;
		private $cadastrado;
		private $modificado;
		private $situacoes_contatos;
			
		public function __construct() { }
			
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}		
					
		public function getContato() {
			return $this->contato;
		}
		
		public function setContato($contato) {
			$this->contato = $contato;
		}		
					
		public function getNome() {
			return $this->nome;
		}
		
		public function setNome($nome) {
			$this->nome = $nome;
		}		
					
		public function getEmail() {
			return $this->email;
		}
		
		public function setEmail($email) {
			$this->email = $email;
		}		
					
		public function getCelular() {
			return $this->celular;
		}
		
		public function setCelular($celular) {
			$this->celular = $celular;
		}		
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}		
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}		
					
		public function getSituacoes_contatos() {
			return $this->situacoes_contatos;
		}
		
		public function setSituacoes_contatos($situacoes_contatos) {
			$this->situacoes_contatos = $situacoes_contatos;
		}		
					
	}
	
?>