<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class CursoOutput implements \JsonSerializable {
			
		private $id;
		private $descricao;
		private $cadastrado;
		private $modificado;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getDescricao() {
			return $this->descricao;
		}
		
		public function setDescricao($descricao) {
			$this->descricao = $descricao;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}

		public function getOutput($curso) {
			if (!is_null($curso)) {
				$cursoOutput = new model\CursoOutput();
				$cursoOutput->setId($curso->getId());
				$cursoOutput->setDescricao($curso->getDescricao());
				return $cursoOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($cursoList) {
			$cursoOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($cursoList); $x++) {
				$cursoOutputList[$count] = $this->getOutput($cursoList[$x]);
				$count++;
			}
			return $cursoOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>