<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class CursoDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = CURSO . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . CURSO . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . CURSO . DOT. DESCRICAO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . CURSO . DOT . DESCRICAO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . CURSO . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . CURSO . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . CURSO . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . CURSO . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($curso) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . CURSO . WHITE_SPACE . LEFT_PARENTHESES . DESCRICAO . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $curso->getDescricao() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $curso->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $curso->getModificado() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$query = SELECT . WHITE_SPACE . $this->columns . WHITE_SPACE . FROM . WHITE_SPACE . CURSO . WHITE_SPACE . CURSO . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$cursoList = array();
			while ($row = $result->fetch_assoc()) {
				$curso = new model\Curso();
				$curso->setId($row[CURSO . POINT . ID]);
				$curso->setDescricao($row[CURSO . POINT . DESCRICAO]);
				$curso->setCadastrado($row[CURSO . POINT . CADASTRADO]);
				$curso->setModificado($row[CURSO . POINT . MODIFICADO]);
				$cursoList[$count] = $curso;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $cursoList;
		}

		public function update($curso) {
			$query = UPDATE . WHITE_SPACE . CURSO . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $curso->getId() . DOUBLE_QUOTES;
			if (!is_null($curso->getDescricao()) && !empty($curso->getDescricao())) {
				$query .= COMMA . WHITE_SPACE . DESCRICAO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$curso->getDescricao() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$curso->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$curso->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($curso) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . CURSO . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $curso->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>