<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class ElementosOutput implements \JsonSerializable {
			
		private $id;
		private $elemento;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $tipos_linhasOutput;
		private $tipos_colunasOutput;
		private $situacoes_registrosOutput;
		private $coresOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getElemento() {
			return $this->elemento;
		}
		
		public function setElemento($elemento) {
			$this->elemento = $elemento;
		}
					
		public function getOrdem() {
			return $this->ordem;
		}
		
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getTipos_linhasOutput() {
			return $this->tipos_linhasOutput;
		}
		
		public function setTipos_linhasOutput($tipos_linhasOutput) {
			$this->tipos_linhasOutput = $tipos_linhasOutput;
		}
					
		public function getTipos_colunasOutput() {
			return $this->tipos_colunasOutput;
		}
		
		public function setTipos_colunasOutput($tipos_colunasOutput) {
			$this->tipos_colunasOutput = $tipos_colunasOutput;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}
					
		public function getCoresOutput() {
			return $this->coresOutput;
		}
		
		public function setCoresOutput($coresOutput) {
			$this->coresOutput = $coresOutput;
		}

		public function getOutput($elementos) {
			if (!is_null($elementos)) {
				$elementosOutput = new model\ElementosOutput();
				$elementosOutput->setId($elementos->getId());
				$elementosOutput->setElemento($elementos->getElemento());
				$elementosOutput->setOrdem($elementos->getOrdem());
				$tipos_linhasOutput = new model\Tipos_linhasOutput();
				$elementosOutput->setTipos_linhasOutput($tipos_linhasOutput->getOutput($elementos->getTipos_linhas()));
				$tipos_colunasOutput = new model\Tipos_colunasOutput();
				$elementosOutput->setTipos_colunasOutput($tipos_colunasOutput->getOutput($elementos->getTipos_colunas()));
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$elementosOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($elementos->getSituacoes_registros()));
				$coresOutput = new model\CoresOutput();
				$elementosOutput->setCoresOutput($coresOutput->getOutput($elementos->getCores()));
				return $elementosOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($elementosList) {
			$elementosOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($elementosList); $x++) {
				$elementosOutputList[$count] = $this->getOutput($elementosList[$x]);
				$count++;
			}
			return $elementosOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>