<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 

	class Elemento_conteudos {
			
		private $id;
		private $elemento_conteudo;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $elementos;
		private $situacoes_registros;
		private $tipos_alinhamentos_horizontais;
		private $tipos_alinhamentos_verticais;
			
		public function __construct() { }
			
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}		
					
		public function getElemento_conteudo() {
			return $this->elemento_conteudo;
		}
		
		public function setElemento_conteudo($elemento_conteudo) {
			$this->elemento_conteudo = $elemento_conteudo;
		}		
					
		public function getOrdem() {
			return $this->ordem;
		}
		
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}		
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}		
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}		
					
		public function getElementos() {
			return $this->elementos;
		}
		
		public function setElementos($elementos) {
			$this->elementos = $elementos;
		}		
					
		public function getSituacoes_registros() {
			return $this->situacoes_registros;
		}
		
		public function setSituacoes_registros($situacoes_registros) {
			$this->situacoes_registros = $situacoes_registros;
		}		
					
		public function getTipos_alinhamentos_horizontais() {
			return $this->tipos_alinhamentos_horizontais;
		}
		
		public function setTipos_alinhamentos_horizontais($tipos_alinhamentos_horizontais) {
			$this->tipos_alinhamentos_horizontais = $tipos_alinhamentos_horizontais;
		}		
					
		public function getTipos_alinhamentos_verticais() {
			return $this->tipos_alinhamentos_verticais;
		}
		
		public function setTipos_alinhamentos_verticais($tipos_alinhamentos_verticais) {
			$this->tipos_alinhamentos_verticais = $tipos_alinhamentos_verticais;
		}		
					
	}
	
?>