<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class ElementosDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = ELEMENTOS . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . ELEMENTOS . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . ELEMENTOS . DOT. ELEMENTO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . ELEMENTOS . DOT . ELEMENTO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . ELEMENTOS . DOT. ORDEM . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . ELEMENTOS . DOT . ORDEM . DOUBLE_QUOTES . COMMA . WHITE_SPACE . ELEMENTOS . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . ELEMENTOS . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . ELEMENTOS . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . ELEMENTOS . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($elementos) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . ELEMENTOS . WHITE_SPACE . LEFT_PARENTHESES . ELEMENTO . COMMA . WHITE_SPACE . ORDEM . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . COMMA . WHITE_SPACE . TIPO_LINHA . COMMA . WHITE_SPACE . TIPO_COLUNA . COMMA . WHITE_SPACE . SITUACAO_REGISTRO . COMMA . WHITE_SPACE . COR . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $elementos->getElemento() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $elementos->getOrdem() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $elementos->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $elementos->getModificado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $elementos->getTipos_linhas()->getId() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $elementos->getTipos_colunas()->getId() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $elementos->getSituacoes_registros()->getId() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $elementos->getCores()->getId() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where . WHITE_SPACE . STRING_AND . WHITE_SPACE . ELEMENTOS . DOT . TIPO_LINHA . WHITE_SPACE . EQUALS . WHITE_SPACE. TIPOS_LINHAS . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . ELEMENTOS . DOT . TIPO_COLUNA . WHITE_SPACE . EQUALS . WHITE_SPACE. TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . ELEMENTOS . DOT . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE. SITUACOES_REGISTROS . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . ELEMENTOS . DOT . COR . WHITE_SPACE . EQUALS . WHITE_SPACE. CORES . DOT . ID;
			} else {
				$where = WHERE . WHITE_SPACE . ELEMENTOS . DOT . TIPO_LINHA . WHITE_SPACE . EQUALS . WHITE_SPACE. TIPOS_LINHAS . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . ELEMENTOS . DOT . TIPO_COLUNA . WHITE_SPACE . EQUALS . WHITE_SPACE. TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . ELEMENTOS . DOT . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE. SITUACOES_REGISTROS . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . ELEMENTOS . DOT . COR . WHITE_SPACE . EQUALS . WHITE_SPACE. CORES . DOT . ID;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$tipos_linhasDao = new model\Tipos_linhasDao($this->connection);
			$tipos_colunasDao = new model\Tipos_colunasDao($this->connection);
			$situacoes_registrosDao = new model\Situacoes_registrosDao($this->connection);
			$coresDao = new model\CoresDao($this->connection);
			$query = SELECT . WHITE_SPACE . $this->columns . COMMA . WHITE_SPACE . $tipos_linhasDao->getColumns() . COMMA . WHITE_SPACE . $tipos_colunasDao->getColumns() . COMMA . WHITE_SPACE . $situacoes_registrosDao->getColumns() . COMMA . WHITE_SPACE . $coresDao->getColumns() . WHITE_SPACE . FROM . WHITE_SPACE . ELEMENTOS . WHITE_SPACE . ELEMENTOS . COMMA . WHITE_SPACE . TIPOS_LINHAS . WHITE_SPACE . TIPOS_LINHAS . COMMA . WHITE_SPACE . TIPOS_COLUNAS . WHITE_SPACE . TIPOS_COLUNAS . COMMA . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . SITUACOES_REGISTROS . COMMA . WHITE_SPACE . CORES . WHITE_SPACE . CORES . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$elementosList = array();
			while ($row = $result->fetch_assoc()) {
				$elementos = new model\Elementos();
				$elementos->setId($row[ELEMENTOS . POINT . ID]);
				$elementos->setElemento($row[ELEMENTOS . POINT . ELEMENTO]);
				$elementos->setOrdem($row[ELEMENTOS . POINT . ORDEM]);
				$elementos->setCadastrado($row[ELEMENTOS . POINT . CADASTRADO]);
				$elementos->setModificado($row[ELEMENTOS . POINT . MODIFICADO]);
				$tipos_linhas = new model\Tipos_linhas();
				$tipos_linhas->setId($row[TIPOS_LINHAS . DOT . ID]);
				$tipos_linhas->setTipo_linha($row[TIPOS_LINHAS . DOT . TIPO_LINHA]);
				$elementos->setTipos_linhas($tipos_linhas);
				$tipos_colunas = new model\Tipos_colunas();
				$tipos_colunas->setId($row[TIPOS_COLUNAS . DOT . ID]);
				$tipos_colunas->setTipo_coluna($row[TIPOS_COLUNAS . DOT . TIPO_COLUNA]);
				$elementos->setTipos_colunas($tipos_colunas);
				$situacoes_registros = new model\Situacoes_registros();
				$situacoes_registros->setId($row[SITUACOES_REGISTROS . DOT . ID]);
				$situacoes_registros->setSituacao_registro($row[SITUACOES_REGISTROS . DOT . SITUACAO_REGISTRO]);
				$elementos->setSituacoes_registros($situacoes_registros);
				$cores = new model\Cores();
				$cores->setId($row[CORES . DOT . ID]);
				$cores->setCor($row[CORES . DOT . COR]);
				$elementos->setCores($cores);
				$elementosList[$count] = $elementos;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $elementosList;
		}

		public function update($elementos) {
			$query = UPDATE . WHITE_SPACE . ELEMENTOS . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $elementos->getId() . DOUBLE_QUOTES;
			if (!is_null($elementos->getElemento()) && !empty($elementos->getElemento())) {
				$query .= COMMA . WHITE_SPACE . ELEMENTO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$elementos->getElemento() . DOUBLE_QUOTES;
			}
			if (!is_null($elementos->getOrdem()) && !empty($elementos->getOrdem())) {
				$query .= COMMA . WHITE_SPACE . ORDEM . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$elementos->getOrdem() . DOUBLE_QUOTES;
			}
			if (!is_null($elementos->getTipos_linhas()) && !empty($elementos->getTipos_linhas()->getId()) &&  
					!empty($elementos->getTipos_linhas()->getId())) {
				$query .= COMMA . WHITE_SPACE . TIPO_LINHA . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$elementos->getTipos_linhas()->getId() . DOUBLE_QUOTES;
			}
			if (!is_null($elementos->getTipos_colunas()) && !empty($elementos->getTipos_colunas()->getId()) &&  
					!empty($elementos->getTipos_colunas()->getId())) {
				$query .= COMMA . WHITE_SPACE . TIPO_COLUNA . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$elementos->getTipos_colunas()->getId() . DOUBLE_QUOTES;
			}
			if (!is_null($elementos->getSituacoes_registros()) && !empty($elementos->getSituacoes_registros()->getId()) &&  
					!empty($elementos->getSituacoes_registros()->getId())) {
				$query .= COMMA . WHITE_SPACE . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$elementos->getSituacoes_registros()->getId() . DOUBLE_QUOTES;
			}
			if (!is_null($elementos->getCores()) && !empty($elementos->getCores()->getId()) &&  
					!empty($elementos->getCores()->getId())) {
				$query .= COMMA . WHITE_SPACE . COR . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$elementos->getCores()->getId() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$elementos->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$elementos->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($elementos) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . ELEMENTOS . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $elementos->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>