<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 

	class Noticias {
			
		private $id;
		private $noticia;
		private $foto;
		private $legenda_foto;
		private $resumo;
		private $conteudo;
		private $palavras_chaves;
		private $cadastrado;
		private $modificado;
		private $usuarios;
		private $situacoes_registros;
		private $tipos_noticias;
			
		public function __construct() { }
			
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}		
					
		public function getNoticia() {
			return $this->noticia;
		}
		
		public function setNoticia($noticia) {
			$this->noticia = $noticia;
		}		
					
		public function getFoto() {
			return $this->foto;
		}
		
		public function setFoto($foto) {
			$this->foto = $foto;
		}		
					
		public function getLegenda_foto() {
			return $this->legenda_foto;
		}
		
		public function setLegenda_foto($legenda_foto) {
			$this->legenda_foto = $legenda_foto;
		}		
					
		public function getResumo() {
			return $this->resumo;
		}
		
		public function setResumo($resumo) {
			$this->resumo = $resumo;
		}		
					
		public function getConteudo() {
			return $this->conteudo;
		}
		
		public function setConteudo($conteudo) {
			$this->conteudo = $conteudo;
		}		
					
		public function getPalavras_chaves() {
			return $this->palavras_chaves;
		}
		
		public function setPalavras_chaves($palavras_chaves) {
			$this->palavras_chaves = $palavras_chaves;
		}		
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}		
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}		
					
		public function getUsuarios() {
			return $this->usuarios;
		}
		
		public function setUsuarios($usuarios) {
			$this->usuarios = $usuarios;
		}		
					
		public function getSituacoes_registros() {
			return $this->situacoes_registros;
		}
		
		public function setSituacoes_registros($situacoes_registros) {
			$this->situacoes_registros = $situacoes_registros;
		}		
					
		public function getTipos_noticias() {
			return $this->tipos_noticias;
		}
		
		public function setTipos_noticias($tipos_noticias) {
			$this->tipos_noticias = $tipos_noticias;
		}		
					
	}
	
?>