<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class NoticiasOutput implements \JsonSerializable {
			
		private $id;
		private $noticia;
		private $foto;
		private $legenda_foto;
		private $resumo;
		private $conteudo;
		private $palavras_chaves;
		private $cadastrado;
		private $modificado;
		private $usuariosOutput;
		private $situacoes_registrosOutput;
		private $tipos_noticiasOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getNoticia() {
			return $this->noticia;
		}
		
		public function setNoticia($noticia) {
			$this->noticia = $noticia;
		}
					
		public function getFoto() {
			return $this->foto;
		}
		
		public function setFoto($foto) {
			$this->foto = $foto;
		}
					
		public function getLegenda_foto() {
			return $this->legenda_foto;
		}
		
		public function setLegenda_foto($legenda_foto) {
			$this->legenda_foto = $legenda_foto;
		}
					
		public function getResumo() {
			return $this->resumo;
		}
		
		public function setResumo($resumo) {
			$this->resumo = $resumo;
		}
					
		public function getConteudo() {
			return $this->conteudo;
		}
		
		public function setConteudo($conteudo) {
			$this->conteudo = $conteudo;
		}
					
		public function getPalavras_chaves() {
			return $this->palavras_chaves;
		}
		
		public function setPalavras_chaves($palavras_chaves) {
			$this->palavras_chaves = $palavras_chaves;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getUsuariosOutput() {
			return $this->usuariosOutput;
		}
		
		public function setUsuariosOutput($usuariosOutput) {
			$this->usuariosOutput = $usuariosOutput;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}
					
		public function getTipos_noticiasOutput() {
			return $this->tipos_noticiasOutput;
		}
		
		public function setTipos_noticiasOutput($tipos_noticiasOutput) {
			$this->tipos_noticiasOutput = $tipos_noticiasOutput;
		}

		public function getOutput($noticias) {
			if (!is_null($noticias)) {
				$noticiasOutput = new model\NoticiasOutput();
				$noticiasOutput->setId($noticias->getId());
				$noticiasOutput->setNoticia($noticias->getNoticia());
				$noticiasOutput->setFoto($noticias->getFoto());
				$noticiasOutput->setLegenda_foto($noticias->getLegenda_foto());
				$noticiasOutput->setResumo($noticias->getResumo());
				$noticiasOutput->setConteudo($noticias->getConteudo());
				$noticiasOutput->setPalavras_chaves($noticias->getPalavras_chaves());
				$usuariosOutput = new model\UsuariosOutput();
				$noticiasOutput->setUsuariosOutput($usuariosOutput->getOutput($noticias->getUsuarios()));
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$noticiasOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($noticias->getSituacoes_registros()));
				$tipos_noticiasOutput = new model\Tipos_noticiasOutput();
				$noticiasOutput->setTipos_noticiasOutput($tipos_noticiasOutput->getOutput($noticias->getTipos_noticias()));
				return $noticiasOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($noticiasList) {
			$noticiasOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($noticiasList); $x++) {
				$noticiasOutputList[$count] = $this->getOutput($noticiasList[$x]);
				$count++;
			}
			return $noticiasOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>