<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class PaginasOutput implements \JsonSerializable {
			
		private $id;
		private $pagina;
		private $conteudo;
		private $palavras_chaves;
		private $cadastrado;
		private $modificado;
		private $situacoes_registrosOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getPagina() {
			return $this->pagina;
		}
		
		public function setPagina($pagina) {
			$this->pagina = $pagina;
		}
					
		public function getConteudo() {
			return $this->conteudo;
		}
		
		public function setConteudo($conteudo) {
			$this->conteudo = $conteudo;
		}
					
		public function getPalavras_chaves() {
			return $this->palavras_chaves;
		}
		
		public function setPalavras_chaves($palavras_chaves) {
			$this->palavras_chaves = $palavras_chaves;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}

		public function getOutput($paginas) {
			if (!is_null($paginas)) {
				$paginasOutput = new model\PaginasOutput();
				$paginasOutput->setId($paginas->getId());
				$paginasOutput->setPagina($paginas->getPagina());
				$paginasOutput->setConteudo($paginas->getConteudo());
				$paginasOutput->setPalavras_chaves($paginas->getPalavras_chaves());
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$paginasOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($paginas->getSituacoes_registros()));
				return $paginasOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($paginasList) {
			$paginasOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($paginasList); $x++) {
				$paginasOutputList[$count] = $this->getOutput($paginasList[$x]);
				$count++;
			}
			return $paginasOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>