<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;
	use src\model;

	class PaginasInput extends getz\Inject {
			
		private $id;
		private $pagina;
		private $conteudo;
		private $palavras_chaves;
		private $cadastrado;
		private $modificado;
		private $situacoes_registrosInput;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}
			if (isset($request[PAGINA])) {
				$this->pagina = $this->inject($request[PAGINA]);	
			}
			if (isset($request[CONTEUDO])) {
				$this->conteudo = $this->inject($request[CONTEUDO]);	
			}
			if (isset($request[PALAVRAS_CHAVES])) {
				$this->palavras_chaves = $this->inject($request[PALAVRAS_CHAVES]);	
			}
			if (isset($request[CADASTRADO])) {
				$this->cadastrado = $this->inject($request[CADASTRADO]);	
			}
			if (isset($request[MODIFICADO])) {
				$this->modificado = $this->inject($request[MODIFICADO]);	
			}
			if (isset($request[SITUACOES_REGISTROS_INPUT]) && isset($request[SITUACOES_REGISTROS_INPUT][ID])) {
				$situacoes_registrosInput = new model\Situacoes_registrosInput($request[SITUACOES_REGISTROS_INPUT]);
				$this->situacoes_registrosInput = $situacoes_registrosInput;	
			}
		}
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getPagina() {
			return $this->pagina;
		}
		
		public function setPagina($pagina) {
			$this->pagina = $pagina;
		}
					
		public function getConteudo() {
			return $this->conteudo;
		}
		
		public function setConteudo($conteudo) {
			$this->conteudo = $conteudo;
		}
					
		public function getPalavras_chaves() {
			return $this->palavras_chaves;
		}
		
		public function setPalavras_chaves($palavras_chaves) {
			$this->palavras_chaves = $palavras_chaves;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getSituacoes_registrosInput() {
			return $this->situacoes_registrosInput;
		}
		
		public function setSituacoes_registrosInput($situacoes_registrosInput) {
			$this->situacoes_registrosInput = $situacoes_registrosInput;
		}	
			
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if (is_null($this->pagina) || empty($this->pagina)) {
					$this->setError(THE_ATTRIBUTE . PAGINA . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->conteudo) || empty($this->conteudo)) {
					$this->setError(THE_ATTRIBUTE . CONTEUDO . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->palavras_chaves) || empty($this->palavras_chaves)) {
					$this->setError(THE_ATTRIBUTE . PALAVRAS_CHAVES . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->situacoes_registrosInput) || is_null($this->situacoes_registrosInput->getId()) || empty($this->situacoes_registrosInput->getId())) {
					$this->setError(THE_ATTRIBUTE . SITUACOES_REGISTROS_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				return true;
			} else if ($method == PUT) {
				if (is_null($this->id) || empty($this->id)) {
					$this->setError(THE_ATTRIBUTE . ID . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
		
		public function getEntity() {
			$paginas = new model\Paginas();
			if (!is_null($this->id)) {
				$paginas->setId($this->id);
			}
			if (!is_null($this->pagina)) {
				$paginas->setPagina($this->pagina);	
			}
			if (!is_null($this->conteudo)) {
				$paginas->setConteudo($this->conteudo);	
			}
			if (!is_null($this->palavras_chaves)) {
				$paginas->setPalavras_chaves($this->palavras_chaves);	
			} 
			$paginas->setCadastrado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			$paginas->setModificado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			if (!is_null($this->situacoes_registrosInput)) {
				$situacoes_registros = $this->situacoes_registrosInput->getEntity();
				$paginas->setSituacoes_registros($situacoes_registros);
			}
			return $paginas;
		}		
		
	}
	
?>