<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class PaginasDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = PAGINAS . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PAGINAS . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PAGINAS . DOT. PAGINA . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PAGINAS . DOT . PAGINA . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PAGINAS . DOT. CONTEUDO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PAGINAS . DOT . CONTEUDO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PAGINAS . DOT. PALAVRAS_CHAVES . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PAGINAS . DOT . PALAVRAS_CHAVES . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PAGINAS . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PAGINAS . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PAGINAS . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PAGINAS . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($paginas) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . PAGINAS . WHITE_SPACE . LEFT_PARENTHESES . PAGINA . COMMA . WHITE_SPACE . CONTEUDO . COMMA . WHITE_SPACE . PALAVRAS_CHAVES . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . COMMA . WHITE_SPACE . SITUACAO_REGISTRO . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $paginas->getPagina() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $paginas->getConteudo() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $paginas->getPalavras_chaves() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $paginas->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $paginas->getModificado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $paginas->getSituacoes_registros()->getId() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where . WHITE_SPACE . STRING_AND . WHITE_SPACE . PAGINAS . DOT . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE. SITUACOES_REGISTROS . DOT . ID;
			} else {
				$where = WHERE . WHITE_SPACE . PAGINAS . DOT . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE. SITUACOES_REGISTROS . DOT . ID;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$situacoes_registrosDao = new model\Situacoes_registrosDao($this->connection);
			$query = SELECT . WHITE_SPACE . $this->columns . COMMA . WHITE_SPACE . $situacoes_registrosDao->getColumns() . WHITE_SPACE . FROM . WHITE_SPACE . PAGINAS . WHITE_SPACE . PAGINAS . COMMA . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$paginasList = array();
			while ($row = $result->fetch_assoc()) {
				$paginas = new model\Paginas();
				$paginas->setId($row[PAGINAS . POINT . ID]);
				$paginas->setPagina($row[PAGINAS . POINT . PAGINA]);
				$paginas->setConteudo($row[PAGINAS . POINT . CONTEUDO]);
				$paginas->setPalavras_chaves($row[PAGINAS . POINT . PALAVRAS_CHAVES]);
				$paginas->setCadastrado($row[PAGINAS . POINT . CADASTRADO]);
				$paginas->setModificado($row[PAGINAS . POINT . MODIFICADO]);
				$situacoes_registros = new model\Situacoes_registros();
				$situacoes_registros->setId($row[SITUACOES_REGISTROS . DOT . ID]);
				$situacoes_registros->setSituacao_registro($row[SITUACOES_REGISTROS . DOT . SITUACAO_REGISTRO]);
				$paginas->setSituacoes_registros($situacoes_registros);
				$paginasList[$count] = $paginas;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $paginasList;
		}

		public function update($paginas) {
			$query = UPDATE . WHITE_SPACE . PAGINAS . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $paginas->getId() . DOUBLE_QUOTES;
			if (!is_null($paginas->getPagina()) && !empty($paginas->getPagina())) {
				$query .= COMMA . WHITE_SPACE . PAGINA . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$paginas->getPagina() . DOUBLE_QUOTES;
			}
			if (!is_null($paginas->getConteudo()) && !empty($paginas->getConteudo())) {
				$query .= COMMA . WHITE_SPACE . CONTEUDO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$paginas->getConteudo() . DOUBLE_QUOTES;
			}
			if (!is_null($paginas->getPalavras_chaves()) && !empty($paginas->getPalavras_chaves())) {
				$query .= COMMA . WHITE_SPACE . PALAVRAS_CHAVES . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$paginas->getPalavras_chaves() . DOUBLE_QUOTES;
			}
			if (!is_null($paginas->getSituacoes_registros()) && !empty($paginas->getSituacoes_registros()->getId()) &&  
					!empty($paginas->getSituacoes_registros()->getId())) {
				$query .= COMMA . WHITE_SPACE . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$paginas->getSituacoes_registros()->getId() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$paginas->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$paginas->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($paginas) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . PAGINAS . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $paginas->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>