<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 

	class Situacoes_contatos {
			
		private $id;
		private $situacao_contato;
		private $cadastrado;
		private $modificado;
		private $cores;
			
		public function __construct() { }
			
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}		
					
		public function getSituacao_contato() {
			return $this->situacao_contato;
		}
		
		public function setSituacao_contato($situacao_contato) {
			$this->situacao_contato = $situacao_contato;
		}		
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}		
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}		
					
		public function getCores() {
			return $this->cores;
		}
		
		public function setCores($cores) {
			$this->cores = $cores;
		}		
					
	}
	
?>