<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class SlidesOutput implements \JsonSerializable {
			
		private $id;
		private $slide;
		private $foto;
		private $link;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $situacoes_registrosOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getSlide() {
			return $this->slide;
		}
		
		public function setSlide($slide) {
			$this->slide = $slide;
		}
					
		public function getFoto() {
			return $this->foto;
		}
		
		public function setFoto($foto) {
			$this->foto = $foto;
		}
					
		public function getLink() {
			return $this->link;
		}
		
		public function setLink($link) {
			$this->link = $link;
		}
					
		public function getOrdem() {
			return $this->ordem;
		}
		
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}

		public function getOutput($slides) {
			if (!is_null($slides)) {
				$slidesOutput = new model\SlidesOutput();
				$slidesOutput->setId($slides->getId());
				$slidesOutput->setSlide($slides->getSlide());
				$slidesOutput->setFoto($slides->getFoto());
				$slidesOutput->setLink($slides->getLink());
				$slidesOutput->setOrdem($slides->getOrdem());
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$slidesOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($slides->getSituacoes_registros()));
				return $slidesOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($slidesList) {
			$slidesOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($slidesList); $x++) {
				$slidesOutputList[$count] = $this->getOutput($slidesList[$x]);
				$count++;
			}
			return $slidesOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>