<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Tipos_linhasOutput implements \JsonSerializable {
			
		private $id;
		private $tipo_linha;
		private $cadastrado;
		private $modificado;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTipo_linha() {
			return $this->tipo_linha;
		}
		
		public function setTipo_linha($tipo_linha) {
			$this->tipo_linha = $tipo_linha;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}

		public function getOutput($tipos_linhas) {
			if (!is_null($tipos_linhas)) {
				$tipos_linhasOutput = new model\Tipos_linhasOutput();
				$tipos_linhasOutput->setId($tipos_linhas->getId());
				$tipos_linhasOutput->setTipo_linha($tipos_linhas->getTipo_linha());
				return $tipos_linhasOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($tipos_linhasList) {
			$tipos_linhasOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($tipos_linhasList); $x++) {
				$tipos_linhasOutputList[$count] = $this->getOutput($tipos_linhasList[$x]);
				$count++;
			}
			return $tipos_linhasOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>