<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class Tipos_noticiasDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = TIPOS_NOTICIAS . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_NOTICIAS . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_NOTICIAS . DOT. TIPO_NOTICIA . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_NOTICIAS . DOT . TIPO_NOTICIA . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_NOTICIAS . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_NOTICIAS . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_NOTICIAS . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_NOTICIAS . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($tipos_noticias) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . TIPOS_NOTICIAS . WHITE_SPACE . LEFT_PARENTHESES . TIPO_NOTICIA . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . COMMA . WHITE_SPACE . COR . COMMA . WHITE_SPACE . SITUACAO_REGISTRO . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $tipos_noticias->getTipo_noticia() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_noticias->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_noticias->getModificado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_noticias->getCores()->getId() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_noticias->getSituacoes_registros()->getId() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where . WHITE_SPACE . STRING_AND . WHITE_SPACE . TIPOS_NOTICIAS . DOT . COR . WHITE_SPACE . EQUALS . WHITE_SPACE. CORES . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . TIPOS_NOTICIAS . DOT . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE. SITUACOES_REGISTROS . DOT . ID;
			} else {
				$where = WHERE . WHITE_SPACE . TIPOS_NOTICIAS . DOT . COR . WHITE_SPACE . EQUALS . WHITE_SPACE. CORES . DOT . ID . WHITE_SPACE . STRING_AND . WHITE_SPACE . TIPOS_NOTICIAS . DOT . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE. SITUACOES_REGISTROS . DOT . ID;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$coresDao = new model\CoresDao($this->connection);
			$situacoes_registrosDao = new model\Situacoes_registrosDao($this->connection);
			$query = SELECT . WHITE_SPACE . $this->columns . COMMA . WHITE_SPACE . $coresDao->getColumns() . COMMA . WHITE_SPACE . $situacoes_registrosDao->getColumns() . WHITE_SPACE . FROM . WHITE_SPACE . TIPOS_NOTICIAS . WHITE_SPACE . TIPOS_NOTICIAS . COMMA . WHITE_SPACE . CORES . WHITE_SPACE . CORES . COMMA . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$tipos_noticiasList = array();
			while ($row = $result->fetch_assoc()) {
				$tipos_noticias = new model\Tipos_noticias();
				$tipos_noticias->setId($row[TIPOS_NOTICIAS . POINT . ID]);
				$tipos_noticias->setTipo_noticia($row[TIPOS_NOTICIAS . POINT . TIPO_NOTICIA]);
				$tipos_noticias->setCadastrado($row[TIPOS_NOTICIAS . POINT . CADASTRADO]);
				$tipos_noticias->setModificado($row[TIPOS_NOTICIAS . POINT . MODIFICADO]);
				$cores = new model\Cores();
				$cores->setId($row[CORES . DOT . ID]);
				$cores->setCor($row[CORES . DOT . COR]);
				$tipos_noticias->setCores($cores);
				$situacoes_registros = new model\Situacoes_registros();
				$situacoes_registros->setId($row[SITUACOES_REGISTROS . DOT . ID]);
				$situacoes_registros->setSituacao_registro($row[SITUACOES_REGISTROS . DOT . SITUACAO_REGISTRO]);
				$tipos_noticias->setSituacoes_registros($situacoes_registros);
				$tipos_noticiasList[$count] = $tipos_noticias;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $tipos_noticiasList;
		}

		public function update($tipos_noticias) {
			$query = UPDATE . WHITE_SPACE . TIPOS_NOTICIAS . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $tipos_noticias->getId() . DOUBLE_QUOTES;
			if (!is_null($tipos_noticias->getTipo_noticia()) && !empty($tipos_noticias->getTipo_noticia())) {
				$query .= COMMA . WHITE_SPACE . TIPO_NOTICIA . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$tipos_noticias->getTipo_noticia() . DOUBLE_QUOTES;
			}
			if (!is_null($tipos_noticias->getCores()) && !empty($tipos_noticias->getCores()->getId()) &&  
					!empty($tipos_noticias->getCores()->getId())) {
				$query .= COMMA . WHITE_SPACE . COR . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$tipos_noticias->getCores()->getId() . DOUBLE_QUOTES;
			}
			if (!is_null($tipos_noticias->getSituacoes_registros()) && !empty($tipos_noticias->getSituacoes_registros()->getId()) &&  
					!empty($tipos_noticias->getSituacoes_registros()->getId())) {
				$query .= COMMA . WHITE_SPACE . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$tipos_noticias->getSituacoes_registros()->getId() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$tipos_noticias->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$tipos_noticias->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($tipos_noticias) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . TIPOS_NOTICIAS . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $tipos_noticias->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>