<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Tipos_noticiasOutput implements \JsonSerializable {
			
		private $id;
		private $tipo_noticia;
		private $cadastrado;
		private $modificado;
		private $coresOutput;
		private $situacoes_registrosOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTipo_noticia() {
			return $this->tipo_noticia;
		}
		
		public function setTipo_noticia($tipo_noticia) {
			$this->tipo_noticia = $tipo_noticia;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getCoresOutput() {
			return $this->coresOutput;
		}
		
		public function setCoresOutput($coresOutput) {
			$this->coresOutput = $coresOutput;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}

		public function getOutput($tipos_noticias) {
			if (!is_null($tipos_noticias)) {
				$tipos_noticiasOutput = new model\Tipos_noticiasOutput();
				$tipos_noticiasOutput->setId($tipos_noticias->getId());
				$tipos_noticiasOutput->setTipo_noticia($tipos_noticias->getTipo_noticia());
				$coresOutput = new model\CoresOutput();
				$tipos_noticiasOutput->setCoresOutput($coresOutput->getOutput($tipos_noticias->getCores()));
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$tipos_noticiasOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($tipos_noticias->getSituacoes_registros()));
				return $tipos_noticiasOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($tipos_noticiasList) {
			$tipos_noticiasOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($tipos_noticiasList); $x++) {
				$tipos_noticiasOutputList[$count] = $this->getOutput($tipos_noticiasList[$x]);
				$count++;
			}
			return $tipos_noticiasOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>