<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;
	use src\model;

	class Tipos_noticiasInput extends getz\Inject {
			
		private $id;
		private $tipo_noticia;
		private $cadastrado;
		private $modificado;
		private $coresInput;
		private $situacoes_registrosInput;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}
			if (isset($request[TIPO_NOTICIA])) {
				$this->tipo_noticia = $this->inject($request[TIPO_NOTICIA]);	
			}
			if (isset($request[CADASTRADO])) {
				$this->cadastrado = $this->inject($request[CADASTRADO]);	
			}
			if (isset($request[MODIFICADO])) {
				$this->modificado = $this->inject($request[MODIFICADO]);	
			}
			if (isset($request[CORES_INPUT]) && isset($request[CORES_INPUT][ID])) {
				$coresInput = new model\CoresInput($request[CORES_INPUT]);
				$this->coresInput = $coresInput;	
			}
			if (isset($request[SITUACOES_REGISTROS_INPUT]) && isset($request[SITUACOES_REGISTROS_INPUT][ID])) {
				$situacoes_registrosInput = new model\Situacoes_registrosInput($request[SITUACOES_REGISTROS_INPUT]);
				$this->situacoes_registrosInput = $situacoes_registrosInput;	
			}
		}
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTipo_noticia() {
			return $this->tipo_noticia;
		}
		
		public function setTipo_noticia($tipo_noticia) {
			$this->tipo_noticia = $tipo_noticia;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getCoresInput() {
			return $this->coresInput;
		}
		
		public function setCoresInput($coresInput) {
			$this->coresInput = $coresInput;
		}
					
		public function getSituacoes_registrosInput() {
			return $this->situacoes_registrosInput;
		}
		
		public function setSituacoes_registrosInput($situacoes_registrosInput) {
			$this->situacoes_registrosInput = $situacoes_registrosInput;
		}	
			
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if (is_null($this->tipo_noticia) || empty($this->tipo_noticia)) {
					$this->setError(THE_ATTRIBUTE . TIPO_NOTICIA . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->coresInput) || is_null($this->coresInput->getId()) || empty($this->coresInput->getId())) {
					$this->setError(THE_ATTRIBUTE . CORES_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->situacoes_registrosInput) || is_null($this->situacoes_registrosInput->getId()) || empty($this->situacoes_registrosInput->getId())) {
					$this->setError(THE_ATTRIBUTE . SITUACOES_REGISTROS_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				return true;
			} else if ($method == PUT) {
				if (is_null($this->id) || empty($this->id)) {
					$this->setError(THE_ATTRIBUTE . ID . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
		
		public function getEntity() {
			$tipos_noticias = new model\Tipos_noticias();
			if (!is_null($this->id)) {
				$tipos_noticias->setId($this->id);
			}
			if (!is_null($this->tipo_noticia)) {
				$tipos_noticias->setTipo_noticia($this->tipo_noticia);	
			} 
			$tipos_noticias->setCadastrado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			$tipos_noticias->setModificado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			if (!is_null($this->coresInput)) {
				$cores = $this->coresInput->getEntity();
				$tipos_noticias->setCores($cores);
			}
			if (!is_null($this->situacoes_registrosInput)) {
				$situacoes_registros = $this->situacoes_registrosInput->getEntity();
				$tipos_noticias->setSituacoes_registros($situacoes_registros);
			}
			return $tipos_noticias;
		}		
		
	}
	
?>