<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 

	class Tipos_noticias {
			
		private $id;
		private $tipo_noticia;
		private $cadastrado;
		private $modificado;
		private $cores;
		private $situacoes_registros;
			
		public function __construct() { }
			
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}		
					
		public function getTipo_noticia() {
			return $this->tipo_noticia;
		}
		
		public function setTipo_noticia($tipo_noticia) {
			$this->tipo_noticia = $tipo_noticia;
		}		
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}		
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}		
					
		public function getCores() {
			return $this->cores;
		}
		
		public function setCores($cores) {
			$this->cores = $cores;
		}		
					
		public function getSituacoes_registros() {
			return $this->situacoes_registros;
		}
		
		public function setSituacoes_registros($situacoes_registros) {
			$this->situacoes_registros = $situacoes_registros;
		}		
					
	}
	
?>