<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Contatos extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$contatosInput = new model\ContatosInput($this->request);
				if ($contatosInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$contatosDao = $this->daoFactory->getContatosDao();
					$result = $contatosDao->create($contatosInput->getEntity());
					$this->log->write(POST, $contatosDao->getLog(), $this->debug);
					$insertId = $contatosDao->getInsertId();
					if ($result) {		
						$contatosList = $contatosDao->read(CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $contatosDao->getLog(), $this->debug);
						$contatosOutput = new model\ContatosOutput();
						$this->response[RESPONSE][CONTATOS][VALUE] = $contatosOutput->getOutputList(
								$contatosList);									
						$this->response[RESPONSE][CONTATOS][SIZE] = sizeOf(
								$this->response[RESPONSE][CONTATOS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $contatosInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = CONTATOS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$contatosDao = $this->daoFactory->getContatosDao();
				$contatosList = $contatosDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $contatosDao->getLog(), $this->debug);
				$contatosOutput = new model\ContatosOutput();
				$this->response[RESPONSE][CONTATOS][VALUE] = $contatosOutput->getOutputList($contatosList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][CONTATOS][SIZE] = $contatosDao->getSize();
					if ($this->response[RESPONSE][CONTATOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][CONTATOS][SIZE] = sizeOf(
							$this->response[RESPONSE][CONTATOS][VALUE]);	
					if ($this->response[RESPONSE][CONTATOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$contatosInput = new model\ContatosInput($this->request);
					if ($contatosInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$contatosDao = $this->daoFactory->getContatosDao();
						$contatosList = $contatosDao->read(CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $contatosDao->getLog(), $this->debug);
						if (!is_null($contatosList) && sizeOf($contatosList) > NUMBER_ZERO) {
							$result = $contatosDao->update($contatosInput->getEntity());
							$this->log->write(PUT, $contatosDao->getLog(), $this->debug);	
							if ($result) {	
								$contatosList = $contatosDao->read(CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $contatosDao->getLog(), $this->debug);
								$contatosOutput = new model\ContatosOutput();
								$this->response[RESPONSE][CONTATOS][VALUE] = $contatosOutput->getOutputList(
										$contatosList);									
								$this->response[RESPONSE][CONTATOS][SIZE] = sizeOf(
										$this->response[RESPONSE][CONTATOS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $contatosInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$contatosDao = $this->daoFactory->getContatosDao();
					$contatosList = $contatosDao->read(CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $contatosDao->getLog(), $this->debug);
					if (!is_null($contatosList) && sizeOf($contatosList) > NUMBER_ZERO) {
						$result = $contatosDao->delete($contatosList[NUMBER_ZERO]);
						$this->log->write(DELETE, $contatosDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>