<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Curso extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$cursoInput = new model\CursoInput($this->request);
				if ($cursoInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$cursoDao = $this->daoFactory->getCursoDao();
					$result = $cursoDao->create($cursoInput->getEntity());
					$this->log->write(POST, $cursoDao->getLog(), $this->debug);
					$insertId = $cursoDao->getInsertId();
					if ($result) {		
						$cursoList = $cursoDao->read(CURSO . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $cursoDao->getLog(), $this->debug);
						$cursoOutput = new model\CursoOutput();
						$this->response[RESPONSE][CURSO][VALUE] = $cursoOutput->getOutputList(
								$cursoList);									
						$this->response[RESPONSE][CURSO][SIZE] = sizeOf(
								$this->response[RESPONSE][CURSO][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $cursoInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = CURSO . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = CURSO . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$cursoDao = $this->daoFactory->getCursoDao();
				$cursoList = $cursoDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $cursoDao->getLog(), $this->debug);
				$cursoOutput = new model\CursoOutput();
				$this->response[RESPONSE][CURSO][VALUE] = $cursoOutput->getOutputList($cursoList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][CURSO][SIZE] = $cursoDao->getSize();
					if ($this->response[RESPONSE][CURSO][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][CURSO][SIZE] = sizeOf(
							$this->response[RESPONSE][CURSO][VALUE]);	
					if ($this->response[RESPONSE][CURSO][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$cursoInput = new model\CursoInput($this->request);
					if ($cursoInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$cursoDao = $this->daoFactory->getCursoDao();
						$cursoList = $cursoDao->read(CURSO . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $cursoDao->getLog(), $this->debug);
						if (!is_null($cursoList) && sizeOf($cursoList) > NUMBER_ZERO) {
							$result = $cursoDao->update($cursoInput->getEntity());
							$this->log->write(PUT, $cursoDao->getLog(), $this->debug);	
							if ($result) {	
								$cursoList = $cursoDao->read(CURSO . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $cursoDao->getLog(), $this->debug);
								$cursoOutput = new model\CursoOutput();
								$this->response[RESPONSE][CURSO][VALUE] = $cursoOutput->getOutputList(
										$cursoList);									
								$this->response[RESPONSE][CURSO][SIZE] = sizeOf(
										$this->response[RESPONSE][CURSO][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $cursoInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$cursoDao = $this->daoFactory->getCursoDao();
					$cursoList = $cursoDao->read(CURSO . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $cursoDao->getLog(), $this->debug);
					if (!is_null($cursoList) && sizeOf($cursoList) > NUMBER_ZERO) {
						$result = $cursoDao->delete($cursoList[NUMBER_ZERO]);
						$this->log->write(DELETE, $cursoDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>