<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Elementos extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$elementosInput = new model\ElementosInput($this->request);
				if ($elementosInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$elementosDao = $this->daoFactory->getElementosDao();
					$result = $elementosDao->create($elementosInput->getEntity());
					$this->log->write(POST, $elementosDao->getLog(), $this->debug);
					$insertId = $elementosDao->getInsertId();
					if ($result) {		
						$elementosList = $elementosDao->read(ELEMENTOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $elementosDao->getLog(), $this->debug);
						$elementosOutput = new model\ElementosOutput();
						$this->response[RESPONSE][ELEMENTOS][VALUE] = $elementosOutput->getOutputList(
								$elementosList);									
						$this->response[RESPONSE][ELEMENTOS][SIZE] = sizeOf(
								$this->response[RESPONSE][ELEMENTOS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $elementosInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = ELEMENTOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = ELEMENTOS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$elementosDao = $this->daoFactory->getElementosDao();
				$elementosList = $elementosDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $elementosDao->getLog(), $this->debug);
				$elementosOutput = new model\ElementosOutput();
				$this->response[RESPONSE][ELEMENTOS][VALUE] = $elementosOutput->getOutputList($elementosList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][ELEMENTOS][SIZE] = $elementosDao->getSize();
					if ($this->response[RESPONSE][ELEMENTOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][ELEMENTOS][SIZE] = sizeOf(
							$this->response[RESPONSE][ELEMENTOS][VALUE]);	
					if ($this->response[RESPONSE][ELEMENTOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$elementosInput = new model\ElementosInput($this->request);
					if ($elementosInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$elementosDao = $this->daoFactory->getElementosDao();
						$elementosList = $elementosDao->read(ELEMENTOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $elementosDao->getLog(), $this->debug);
						if (!is_null($elementosList) && sizeOf($elementosList) > NUMBER_ZERO) {
							$result = $elementosDao->update($elementosInput->getEntity());
							$this->log->write(PUT, $elementosDao->getLog(), $this->debug);	
							if ($result) {	
								$elementosList = $elementosDao->read(ELEMENTOS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $elementosDao->getLog(), $this->debug);
								$elementosOutput = new model\ElementosOutput();
								$this->response[RESPONSE][ELEMENTOS][VALUE] = $elementosOutput->getOutputList(
										$elementosList);									
								$this->response[RESPONSE][ELEMENTOS][SIZE] = sizeOf(
										$this->response[RESPONSE][ELEMENTOS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $elementosInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$elementosDao = $this->daoFactory->getElementosDao();
					$elementosList = $elementosDao->read(ELEMENTOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $elementosDao->getLog(), $this->debug);
					if (!is_null($elementosList) && sizeOf($elementosList) > NUMBER_ZERO) {
						$result = $elementosDao->delete($elementosList[NUMBER_ZERO]);
						$this->log->write(DELETE, $elementosDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>