<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Elemento_conteudos extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$elemento_conteudosInput = new model\Elemento_conteudosInput($this->request);
				if ($elemento_conteudosInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$elemento_conteudosDao = $this->daoFactory->getElemento_conteudosDao();
					$result = $elemento_conteudosDao->create($elemento_conteudosInput->getEntity());
					$this->log->write(POST, $elemento_conteudosDao->getLog(), $this->debug);
					$insertId = $elemento_conteudosDao->getInsertId();
					if ($result) {		
						$elemento_conteudosList = $elemento_conteudosDao->read(ELEMENTO_CONTEUDOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $elemento_conteudosDao->getLog(), $this->debug);
						$elemento_conteudosOutput = new model\Elemento_conteudosOutput();
						$this->response[RESPONSE][ELEMENTO_CONTEUDOS][VALUE] = $elemento_conteudosOutput->getOutputList(
								$elemento_conteudosList);									
						$this->response[RESPONSE][ELEMENTO_CONTEUDOS][SIZE] = sizeOf(
								$this->response[RESPONSE][ELEMENTO_CONTEUDOS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $elemento_conteudosInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = ELEMENTO_CONTEUDOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = ELEMENTO_CONTEUDOS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$elemento_conteudosDao = $this->daoFactory->getElemento_conteudosDao();
				$elemento_conteudosList = $elemento_conteudosDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $elemento_conteudosDao->getLog(), $this->debug);
				$elemento_conteudosOutput = new model\Elemento_conteudosOutput();
				$this->response[RESPONSE][ELEMENTO_CONTEUDOS][VALUE] = $elemento_conteudosOutput->getOutputList($elemento_conteudosList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][ELEMENTO_CONTEUDOS][SIZE] = $elemento_conteudosDao->getSize();
					if ($this->response[RESPONSE][ELEMENTO_CONTEUDOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][ELEMENTO_CONTEUDOS][SIZE] = sizeOf(
							$this->response[RESPONSE][ELEMENTO_CONTEUDOS][VALUE]);	
					if ($this->response[RESPONSE][ELEMENTO_CONTEUDOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$elemento_conteudosInput = new model\Elemento_conteudosInput($this->request);
					if ($elemento_conteudosInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$elemento_conteudosDao = $this->daoFactory->getElemento_conteudosDao();
						$elemento_conteudosList = $elemento_conteudosDao->read(ELEMENTO_CONTEUDOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $elemento_conteudosDao->getLog(), $this->debug);
						if (!is_null($elemento_conteudosList) && sizeOf($elemento_conteudosList) > NUMBER_ZERO) {
							$result = $elemento_conteudosDao->update($elemento_conteudosInput->getEntity());
							$this->log->write(PUT, $elemento_conteudosDao->getLog(), $this->debug);	
							if ($result) {	
								$elemento_conteudosList = $elemento_conteudosDao->read(ELEMENTO_CONTEUDOS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $elemento_conteudosDao->getLog(), $this->debug);
								$elemento_conteudosOutput = new model\Elemento_conteudosOutput();
								$this->response[RESPONSE][ELEMENTO_CONTEUDOS][VALUE] = $elemento_conteudosOutput->getOutputList(
										$elemento_conteudosList);									
								$this->response[RESPONSE][ELEMENTO_CONTEUDOS][SIZE] = sizeOf(
										$this->response[RESPONSE][ELEMENTO_CONTEUDOS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $elemento_conteudosInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$elemento_conteudosDao = $this->daoFactory->getElemento_conteudosDao();
					$elemento_conteudosList = $elemento_conteudosDao->read(ELEMENTO_CONTEUDOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $elemento_conteudosDao->getLog(), $this->debug);
					if (!is_null($elemento_conteudosList) && sizeOf($elemento_conteudosList) > NUMBER_ZERO) {
						$result = $elemento_conteudosDao->delete($elemento_conteudosList[NUMBER_ZERO]);
						$this->log->write(DELETE, $elemento_conteudosDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>