<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Noticias extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$noticiasInput = new model\NoticiasInput($this->request);
				if ($noticiasInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$noticiasDao = $this->daoFactory->getNoticiasDao();
					if ($noticiasInput->getFoto() != null) {
						$file = new getz\File($noticiasInput->getFoto());
						$file->moveToImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT);
						$noticiasInput->setFoto($file->getName());
					}
					$result = $noticiasDao->create($noticiasInput->getEntity());
					$this->log->write(POST, $noticiasDao->getLog(), $this->debug);
					$insertId = $noticiasDao->getInsertId();
					if ($result) {		
						$noticiasList = $noticiasDao->read(NOTICIAS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $noticiasDao->getLog(), $this->debug);
						$noticiasOutput = new model\NoticiasOutput();
						$this->response[RESPONSE][NOTICIAS][VALUE] = $noticiasOutput->getOutputList(
								$noticiasList);									
						$this->response[RESPONSE][NOTICIAS][SIZE] = sizeOf(
								$this->response[RESPONSE][NOTICIAS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $noticiasInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = NOTICIAS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = NOTICIAS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$noticiasDao = $this->daoFactory->getNoticiasDao();
				$noticiasList = $noticiasDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $noticiasDao->getLog(), $this->debug);
				$noticiasOutput = new model\NoticiasOutput();
				$this->response[RESPONSE][NOTICIAS][VALUE] = $noticiasOutput->getOutputList($noticiasList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][NOTICIAS][SIZE] = $noticiasDao->getSize();
					if ($this->response[RESPONSE][NOTICIAS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][NOTICIAS][SIZE] = sizeOf(
							$this->response[RESPONSE][NOTICIAS][VALUE]);	
					if ($this->response[RESPONSE][NOTICIAS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$noticiasInput = new model\NoticiasInput($this->request);
					if ($noticiasInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$noticiasDao = $this->daoFactory->getNoticiasDao();
						$noticiasList = $noticiasDao->read(NOTICIAS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $noticiasDao->getLog(), $this->debug);
						if (!is_null($noticiasList) && sizeOf($noticiasList) > NUMBER_ZERO) {
							if ($noticiasInput->getFoto() != null) {
								$file = new getz\File($noticiasInput->getFoto());
								if ($noticiasList[NUMBER_ZERO]->getFoto != STRING_EMPTY) {
									$file->deleteImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT, $noticiasList[NUMBER_ZERO]->getFoto);
								}
								$file->moveToImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT);
								$noticiasInput->setFoto($file->getName());
							}
							$result = $noticiasDao->update($noticiasInput->getEntity());
							$this->log->write(PUT, $noticiasDao->getLog(), $this->debug);	
							if ($result) {	
								$noticiasList = $noticiasDao->read(NOTICIAS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $noticiasDao->getLog(), $this->debug);
								$noticiasOutput = new model\NoticiasOutput();
								$this->response[RESPONSE][NOTICIAS][VALUE] = $noticiasOutput->getOutputList(
										$noticiasList);									
								$this->response[RESPONSE][NOTICIAS][SIZE] = sizeOf(
										$this->response[RESPONSE][NOTICIAS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $noticiasInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$noticiasDao = $this->daoFactory->getNoticiasDao();
					$noticiasList = $noticiasDao->read(NOTICIAS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $noticiasDao->getLog(), $this->debug);
					if (!is_null($noticiasList) && sizeOf($noticiasList) > NUMBER_ZERO) {
						$file = new getz\File(STRING_EMPTY);
						if ($noticiasList[NUMBER_ZERO]->getFoto != STRING_EMPTY) {
							$file->deleteImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT, $noticiasList[NUMBER_ZERO]->getFoto);
						}
						$result = $noticiasDao->delete($noticiasList[NUMBER_ZERO]);
						$this->log->write(DELETE, $noticiasDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>