<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Paginas extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$paginasInput = new model\PaginasInput($this->request);
				if ($paginasInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$paginasDao = $this->daoFactory->getPaginasDao();
					$result = $paginasDao->create($paginasInput->getEntity());
					$this->log->write(POST, $paginasDao->getLog(), $this->debug);
					$insertId = $paginasDao->getInsertId();
					if ($result) {		
						$paginasList = $paginasDao->read(PAGINAS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $paginasDao->getLog(), $this->debug);
						$paginasOutput = new model\PaginasOutput();
						$this->response[RESPONSE][PAGINAS][VALUE] = $paginasOutput->getOutputList(
								$paginasList);									
						$this->response[RESPONSE][PAGINAS][SIZE] = sizeOf(
								$this->response[RESPONSE][PAGINAS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $paginasInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = PAGINAS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = PAGINAS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$paginasDao = $this->daoFactory->getPaginasDao();
				$paginasList = $paginasDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $paginasDao->getLog(), $this->debug);
				$paginasOutput = new model\PaginasOutput();
				$this->response[RESPONSE][PAGINAS][VALUE] = $paginasOutput->getOutputList($paginasList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][PAGINAS][SIZE] = $paginasDao->getSize();
					if ($this->response[RESPONSE][PAGINAS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][PAGINAS][SIZE] = sizeOf(
							$this->response[RESPONSE][PAGINAS][VALUE]);	
					if ($this->response[RESPONSE][PAGINAS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$paginasInput = new model\PaginasInput($this->request);
					if ($paginasInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$paginasDao = $this->daoFactory->getPaginasDao();
						$paginasList = $paginasDao->read(PAGINAS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $paginasDao->getLog(), $this->debug);
						if (!is_null($paginasList) && sizeOf($paginasList) > NUMBER_ZERO) {
							$result = $paginasDao->update($paginasInput->getEntity());
							$this->log->write(PUT, $paginasDao->getLog(), $this->debug);	
							if ($result) {	
								$paginasList = $paginasDao->read(PAGINAS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $paginasDao->getLog(), $this->debug);
								$paginasOutput = new model\PaginasOutput();
								$this->response[RESPONSE][PAGINAS][VALUE] = $paginasOutput->getOutputList(
										$paginasList);									
								$this->response[RESPONSE][PAGINAS][SIZE] = sizeOf(
										$this->response[RESPONSE][PAGINAS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $paginasInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$paginasDao = $this->daoFactory->getPaginasDao();
					$paginasList = $paginasDao->read(PAGINAS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $paginasDao->getLog(), $this->debug);
					if (!is_null($paginasList) && sizeOf($paginasList) > NUMBER_ZERO) {
						$result = $paginasDao->delete($paginasList[NUMBER_ZERO]);
						$this->log->write(DELETE, $paginasDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>