<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Situacoes_contatos extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$situacoes_contatosInput = new model\Situacoes_contatosInput($this->request);
				if ($situacoes_contatosInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$situacoes_contatosDao = $this->daoFactory->getSituacoes_contatosDao();
					$result = $situacoes_contatosDao->create($situacoes_contatosInput->getEntity());
					$this->log->write(POST, $situacoes_contatosDao->getLog(), $this->debug);
					$insertId = $situacoes_contatosDao->getInsertId();
					if ($result) {		
						$situacoes_contatosList = $situacoes_contatosDao->read(SITUACOES_CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $situacoes_contatosDao->getLog(), $this->debug);
						$situacoes_contatosOutput = new model\Situacoes_contatosOutput();
						$this->response[RESPONSE][SITUACOES_CONTATOS][VALUE] = $situacoes_contatosOutput->getOutputList(
								$situacoes_contatosList);									
						$this->response[RESPONSE][SITUACOES_CONTATOS][SIZE] = sizeOf(
								$this->response[RESPONSE][SITUACOES_CONTATOS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $situacoes_contatosInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = SITUACOES_CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = SITUACOES_CONTATOS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$situacoes_contatosDao = $this->daoFactory->getSituacoes_contatosDao();
				$situacoes_contatosList = $situacoes_contatosDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $situacoes_contatosDao->getLog(), $this->debug);
				$situacoes_contatosOutput = new model\Situacoes_contatosOutput();
				$this->response[RESPONSE][SITUACOES_CONTATOS][VALUE] = $situacoes_contatosOutput->getOutputList($situacoes_contatosList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][SITUACOES_CONTATOS][SIZE] = $situacoes_contatosDao->getSize();
					if ($this->response[RESPONSE][SITUACOES_CONTATOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][SITUACOES_CONTATOS][SIZE] = sizeOf(
							$this->response[RESPONSE][SITUACOES_CONTATOS][VALUE]);	
					if ($this->response[RESPONSE][SITUACOES_CONTATOS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$situacoes_contatosInput = new model\Situacoes_contatosInput($this->request);
					if ($situacoes_contatosInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$situacoes_contatosDao = $this->daoFactory->getSituacoes_contatosDao();
						$situacoes_contatosList = $situacoes_contatosDao->read(SITUACOES_CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $situacoes_contatosDao->getLog(), $this->debug);
						if (!is_null($situacoes_contatosList) && sizeOf($situacoes_contatosList) > NUMBER_ZERO) {
							$result = $situacoes_contatosDao->update($situacoes_contatosInput->getEntity());
							$this->log->write(PUT, $situacoes_contatosDao->getLog(), $this->debug);	
							if ($result) {	
								$situacoes_contatosList = $situacoes_contatosDao->read(SITUACOES_CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $situacoes_contatosDao->getLog(), $this->debug);
								$situacoes_contatosOutput = new model\Situacoes_contatosOutput();
								$this->response[RESPONSE][SITUACOES_CONTATOS][VALUE] = $situacoes_contatosOutput->getOutputList(
										$situacoes_contatosList);									
								$this->response[RESPONSE][SITUACOES_CONTATOS][SIZE] = sizeOf(
										$this->response[RESPONSE][SITUACOES_CONTATOS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $situacoes_contatosInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$situacoes_contatosDao = $this->daoFactory->getSituacoes_contatosDao();
					$situacoes_contatosList = $situacoes_contatosDao->read(SITUACOES_CONTATOS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $situacoes_contatosDao->getLog(), $this->debug);
					if (!is_null($situacoes_contatosList) && sizeOf($situacoes_contatosList) > NUMBER_ZERO) {
						$result = $situacoes_contatosDao->delete($situacoes_contatosList[NUMBER_ZERO]);
						$this->log->write(DELETE, $situacoes_contatosDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>