<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Slides extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$slidesInput = new model\SlidesInput($this->request);
				if ($slidesInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$slidesDao = $this->daoFactory->getSlidesDao();
					if ($slidesInput->getFoto() != null) {
						$file = new getz\File($slidesInput->getFoto());
						$file->moveToImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT);
						$slidesInput->setFoto($file->getName());
					}
					$result = $slidesDao->create($slidesInput->getEntity());
					$this->log->write(POST, $slidesDao->getLog(), $this->debug);
					$insertId = $slidesDao->getInsertId();
					if ($result) {		
						$slidesList = $slidesDao->read(SLIDES . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $slidesDao->getLog(), $this->debug);
						$slidesOutput = new model\SlidesOutput();
						$this->response[RESPONSE][SLIDES][VALUE] = $slidesOutput->getOutputList(
								$slidesList);									
						$this->response[RESPONSE][SLIDES][SIZE] = sizeOf(
								$this->response[RESPONSE][SLIDES][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $slidesInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = SLIDES . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = SLIDES . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$slidesDao = $this->daoFactory->getSlidesDao();
				$slidesList = $slidesDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $slidesDao->getLog(), $this->debug);
				$slidesOutput = new model\SlidesOutput();
				$this->response[RESPONSE][SLIDES][VALUE] = $slidesOutput->getOutputList($slidesList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][SLIDES][SIZE] = $slidesDao->getSize();
					if ($this->response[RESPONSE][SLIDES][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][SLIDES][SIZE] = sizeOf(
							$this->response[RESPONSE][SLIDES][VALUE]);	
					if ($this->response[RESPONSE][SLIDES][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$slidesInput = new model\SlidesInput($this->request);
					if ($slidesInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$slidesDao = $this->daoFactory->getSlidesDao();
						$slidesList = $slidesDao->read(SLIDES . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $slidesDao->getLog(), $this->debug);
						if (!is_null($slidesList) && sizeOf($slidesList) > NUMBER_ZERO) {
							if ($slidesInput->getFoto() != null) {
								$file = new getz\File($slidesInput->getFoto());
								if ($slidesList[NUMBER_ZERO]->getFoto != STRING_EMPTY) {
									$file->deleteImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT, $slidesList[NUMBER_ZERO]->getFoto);
								}
								$file->moveToImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT);
								$slidesInput->setFoto($file->getName());
							}
							$result = $slidesDao->update($slidesInput->getEntity());
							$this->log->write(PUT, $slidesDao->getLog(), $this->debug);	
							if ($result) {	
								$slidesList = $slidesDao->read(SLIDES . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $slidesDao->getLog(), $this->debug);
								$slidesOutput = new model\SlidesOutput();
								$this->response[RESPONSE][SLIDES][VALUE] = $slidesOutput->getOutputList(
										$slidesList);									
								$this->response[RESPONSE][SLIDES][SIZE] = sizeOf(
										$this->response[RESPONSE][SLIDES][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $slidesInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$slidesDao = $this->daoFactory->getSlidesDao();
					$slidesList = $slidesDao->read(SLIDES . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $slidesDao->getLog(), $this->debug);
					if (!is_null($slidesList) && sizeOf($slidesList) > NUMBER_ZERO) {
						$file = new getz\File(STRING_EMPTY);
						if ($slidesList[NUMBER_ZERO]->getFoto != STRING_EMPTY) {
							$file->deleteImg($this->documentRoot, PROJECT . HYPHEN . API, PROJECT, $slidesList[NUMBER_ZERO]->getFoto);
						}
						$result = $slidesDao->delete($slidesList[NUMBER_ZERO]);
						$this->log->write(DELETE, $slidesDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>