<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Tipos_colunas extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$tipos_colunasInput = new model\Tipos_colunasInput($this->request);
				if ($tipos_colunasInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$tipos_colunasDao = $this->daoFactory->getTipos_colunasDao();
					$result = $tipos_colunasDao->create($tipos_colunasInput->getEntity());
					$this->log->write(POST, $tipos_colunasDao->getLog(), $this->debug);
					$insertId = $tipos_colunasDao->getInsertId();
					if ($result) {		
						$tipos_colunasList = $tipos_colunasDao->read(TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $tipos_colunasDao->getLog(), $this->debug);
						$tipos_colunasOutput = new model\Tipos_colunasOutput();
						$this->response[RESPONSE][TIPOS_COLUNAS][VALUE] = $tipos_colunasOutput->getOutputList(
								$tipos_colunasList);									
						$this->response[RESPONSE][TIPOS_COLUNAS][SIZE] = sizeOf(
								$this->response[RESPONSE][TIPOS_COLUNAS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $tipos_colunasInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$tipos_colunasDao = $this->daoFactory->getTipos_colunasDao();
				$tipos_colunasList = $tipos_colunasDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $tipos_colunasDao->getLog(), $this->debug);
				$tipos_colunasOutput = new model\Tipos_colunasOutput();
				$this->response[RESPONSE][TIPOS_COLUNAS][VALUE] = $tipos_colunasOutput->getOutputList($tipos_colunasList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][TIPOS_COLUNAS][SIZE] = $tipos_colunasDao->getSize();
					if ($this->response[RESPONSE][TIPOS_COLUNAS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][TIPOS_COLUNAS][SIZE] = sizeOf(
							$this->response[RESPONSE][TIPOS_COLUNAS][VALUE]);	
					if ($this->response[RESPONSE][TIPOS_COLUNAS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$tipos_colunasInput = new model\Tipos_colunasInput($this->request);
					if ($tipos_colunasInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$tipos_colunasDao = $this->daoFactory->getTipos_colunasDao();
						$tipos_colunasList = $tipos_colunasDao->read(TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $tipos_colunasDao->getLog(), $this->debug);
						if (!is_null($tipos_colunasList) && sizeOf($tipos_colunasList) > NUMBER_ZERO) {
							$result = $tipos_colunasDao->update($tipos_colunasInput->getEntity());
							$this->log->write(PUT, $tipos_colunasDao->getLog(), $this->debug);	
							if ($result) {	
								$tipos_colunasList = $tipos_colunasDao->read(TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $tipos_colunasDao->getLog(), $this->debug);
								$tipos_colunasOutput = new model\Tipos_colunasOutput();
								$this->response[RESPONSE][TIPOS_COLUNAS][VALUE] = $tipos_colunasOutput->getOutputList(
										$tipos_colunasList);									
								$this->response[RESPONSE][TIPOS_COLUNAS][SIZE] = sizeOf(
										$this->response[RESPONSE][TIPOS_COLUNAS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $tipos_colunasInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$tipos_colunasDao = $this->daoFactory->getTipos_colunasDao();
					$tipos_colunasList = $tipos_colunasDao->read(TIPOS_COLUNAS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $tipos_colunasDao->getLog(), $this->debug);
					if (!is_null($tipos_colunasList) && sizeOf($tipos_colunasList) > NUMBER_ZERO) {
						$result = $tipos_colunasDao->delete($tipos_colunasList[NUMBER_ZERO]);
						$this->log->write(DELETE, $tipos_colunasDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>